# Generated by Django 5.0.6 on 2024-06-02 15:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Desconhecido', max_length=255)),
                ('cnpj', models.CharField(default='00000000000000', max_length=14)),
                ('cep', models.CharField(default='00000000', max_length=8)),
                ('email', models.EmailField(default='email@exemplo.com', max_length=254)),
                ('rua', models.CharField(default='Desconhecido', max_length=255)),
                ('bairro', models.CharField(default='Desconhecido', max_length=255)),
                ('cidade', models.CharField(default='Desconhecida', max_length=255)),
                ('estado', models.CharField(default='SP', max_length=2)),
                ('telefone', models.CharField(default='(00) 00000-0000', max_length=20)),
                ('site', models.URLField(default='http://www.exemplo.com')),
                ('observacoes', models.TextField(default='Sem observações')),
                ('contato', models.CharField(default='Desconhecido', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_servico', models.TextField()),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='ordens_servico/fotos/')),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
                ('hora_criacao', models.TimeField(default=django.utils.timezone.now)),
                ('km_saida', models.CharField(default='0', max_length=50)),
                ('km_chegada', models.CharField(default='0', max_length=50)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('observacoes', models.TextField(default='Sem observações')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('concluido', 'Concluído'), ('pendente', 'Pendente')], default='aberto', max_length=20)),
                ('cliente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='os_project.cliente')),
                ('tecnico_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
