# Generated by Django 5.0.6 on 2024-06-02 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('os_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='fotos',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='km_chegada',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='km_saida',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='os_project.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
